# Generated by Django 6.0.6 on 2026-06-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hero_title",
                    models.CharField(
                        default="Empowering\nFuture Engineers", max_length=255
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="RIT is committed to providing quality education, innovative research and holistic development to build competent professionals for a better tomorrow."
                    ),
                ),
                (
                    "hero_image_url",
                    models.CharField(default="/rit1.PNG", max_length=500),
                ),
                (
                    "about_badge",
                    models.CharField(default="RIT Profile", max_length=100),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="About Ramco Institute of Technology", max_length=255
                    ),
                ),
                (
                    "about_lead",
                    models.TextField(
                        default="Ramco Institute of Technology was founded with a vision to impart high-quality engineering education at an affordable cost. Under the guidance of our Chairman Shri P.R. Venketrama Raja, we revolutionize the learning environment."
                    ),
                ),
                (
                    "about_description",
                    models.TextField(
                        default="Being part of the Ramco Group, widely recognized for its qualitative and innovative brands globally, we set high standards. We empower students with accessible, yet world-class engineering education and prepare them for lifelong learning."
                    ),
                ),
                (
                    "about_image_url",
                    models.CharField(default="/rit.JPG", max_length=500),
                ),
                ("about_estd", models.CharField(default="2013", max_length=50)),
                (
                    "vision_text",
                    models.TextField(
                        default="To evolve as an Institute of international repute in offering high-quality technical education, Research and extension programmes in order to create knowledgeable, professionally competent and skilled Engineers and Technologists capable of working in multi-disciplinary environment to cater to the societal needs."
                    ),
                ),
                (
                    "mission_intro",
                    models.TextField(
                        default="To accomplish its unique vision, the Institute has a far-reaching mission that aims:"
                    ),
                ),
                (
                    "mission_points",
                    models.JSONField(
                        blank=True, default=list, help_text="List of mission points"
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True, default=list, help_text="List of stats objects"
                    ),
                ),
                (
                    "homepage_images",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary of image keys and their URLs",
                    ),
                ),
                (
                    "cta_buttons",
                    models.JSONField(
                        blank=True, default=list, help_text="List of CTA buttons"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="news",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="news_thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="thumbnail_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
