# Generated by Django 5.2.14 on 2026-06-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_homepageconfig_news_thumbnail_news_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='news',
            name='document_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
