# Generated by Django 5.2.14 on 2026-06-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_news_document_news_document_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='document',
        ),
        migrations.RemoveField(
            model_name='news',
            name='document_url',
        ),
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
